<?php

namespace App\Http\Resources;

use Illuminate\Http\Resources\Json\JsonResource;

class clericalPageResource extends JsonResource
{
    /**
     * Transform the resource into an array.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array|\Illuminate\Contracts\Support\Arrayable|\JsonSerializable
     */
    public function toArray($request)
    {
        return [
            'id'=>$this->id,
            'full_name'=>$this->full_name,
            'city'=>$this->city,
            'date'=>$this->date,
            'ssn'=>$this->ssn,
            'address'=>$this->address,
            'city'=>$this->city,
            'state'=>$this->state,
            'zipcode'=>$this->zipcode,
            'home_telephone'=>$this->home_telephone,
            'other_phone'=>$this->other_phone,
            'eighteen_plus' => $this->eighteen_plus,
            'date_available'=>$this->date_of_available,
            'position'=>$this->how_find_position,
            'any_relative'=>$this->any_relative,
            'please_list'=>$this->please_list,
            'position_apply_for'=> $this->position_apply_for,
            'ever_worked'=>$this->ever_worked,
            'worked_dates'=>$this->worked_dates,
            'prior_position'=>$this->prior_position,
            'leaving_reason'=>$this->leaving_reason,
            'cpr_certificate_number'=>$this->cpr_certificate_number,
            'cpr_expiry_date'=>$this->cpr_expiry_date,
            'cpr_agency'=>$this->cpr_agency,
            'cdl_certificate_number'=>$this->cdl_certificate_number,
            'cdl_expiry_date'=>$this->cdl_expiry_date,
            'cdl_agency'=>$this->cdl_agency,
            'defensive_certificate_number'=>$this->defensive_certificate_number,
            'defensive_expiry_date'=>$this->defensive_expiry_date,
            'defensive_agency'=>$this->defensive_agency,
            'other_certificate_number'=>$this->other_certificate_number,
            'other_expiry_date'=>$this->other_expiry_date,
            'other_agency'=>$this->other_agency,
            'eligible_proof'=>$this->eligible_proof,
            'valid_driving_license'=>$this->valid_driving_license,
            'class'=>$this->class,
            'issued_state'=>$this->issued_state,
            'driving_license'=>$this->driving_license,
            'moving_violation'=>$this->moving_violation,
            'ever_conviced'=>$this->ever_conviced,
            'ever_conviced_explain'=>$this->ever_conviced_explain,
            'ever_excluded'=>$this->ever_excluded,
            'ever_excluded_yes'=>$this->ever_excluded_yes,
            'is_step3_approved'=>$this->is_step3_approved,
            'is_final_approved'=>$this->is_final_approved,
            'school_name'=>$this->school_name,
            'school_address'=>$this->school_address,
            'school_years'=>$this->school_years,
            'school_graduate'=>$this->school_graduate,
            'ged'=>$this->ged,
            'college_name'=>$this->college_name,
            'college_address'=>$this->college_address,
            'college_years'=>$this->college_years,
            'college_graduate'=>$this->college_graduate,
            'college_highest_grade'=>$this->college_highest_grade,
            'degree'=>$this->degree,
            'major'=>$this->major,
            'other_college_name'=>$this->other_college_name,
            'other_college_address'=>$this->other_college_address,
            'other_college_years'=>$this->other_college_years,
            'other_college_graduate'=>$this->other_college_graduate,
            'other_college_higesht_grade'=>$this->other_college_higesht_grade,
            'other_college_major'=>$this->other_college_major,
            'tech_name'=>$this->tech_name,
            'tech_address'=>$this->tech_address,
            'tech_year'=>$this->tech_year,
            'tech_graduate'=>$this->tech_graduate,
            'tech_highest_grade'=>$this->tech_highest_grade,
            'tech_certificate'=>$this->tech_certificate,
            'tech_license'=>$this->tech_license,
            'tech_expires'=>$this->tech_expires,
            'other_school_name'=>$this->other_school_name,
            'other_school_address'=>$this->other_school_address,
            'other_school_years'=>$this->other_school_years,
            'other_school_graduate'=>$this->other_school_graduate,
            'other_school_higest_grade'=>$this->other_school_higest_grade,
            'other_school_certificate'=>$this->other_school_certificate,
            'other_school_license'=>$this->other_school_license,
            'other_school_expires'=>$this->other_school_expires,
            'other_school_other'=>$this->other_school_other,
            'ems_training'=>$this->ems_training,
            'ems_professional'=>$this->ems_professional,
            'additional_qualification'=>$this->additional_qualification,
            'app_date'=>$this->app_date,
            'signed'=>$this->signed,
            'via_email'=>$this->via_email,
            'military_branch'=>$this->military_branch,
            'military_began'=>$this->military_began,
            'military_ended'=>$this->military_ended,
            'military_rank'=>$this->military_rank,
            'military_discharged'=>$this->military_discharged,
            'military_location'=>$this->military_location,
            'gap_in_employment'=>$this->gap_in_employment,
            'disciplined'=>$this->disciplined,
            'probation'=>$this->probation,
            'fired_violation'=>$this->fired_violation,
            'fired_assault'=>$this->fired_assault,
            'fired_harassment'=>$this->fired_harassment,
            'fired_patient'=>$this->fired_patient,
            'fired_alcohol'=>$this->fired_alcohol,
            'charged_dui'=>$this->charged_dui,
            'past_explain'=>$this->past_explain,
            'school_name'=>$this->school_name,
            'school_address'=>$this->school_address,
            'school_years'=>$this->school_years,
            'tech_address'=>$this->tech_address,
            'tech_year'=>$this->tech_year,
            'tech_graduate'=>$this->tech_graduate,
            'tech_highest_grade'=>$this->tech_highest_grade,
            'tech_certificate'=>$this->tech_certificate,
            'tech_license'=>$this->tech_license,
            'employer_detail'=>$this->previousEmployeers,


        ];
    }
}
